version: "3"

services:
  node_1:
    container_name: mycassandra1
    image: cassandra:4.0.4
    ports:
      - 9042:9042
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
      - ./config:/home/config/
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=1g
      - MAX_HEAP_SIZE=2g
    healthcheck:
      test:
        [
          "CMD",
          "cqlsh",
          "-e",
          "select count(*) from testvalidation.sampletable"
        ]
      interval: 5s
      timeout: 5s
      retries: 60
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4g"
