# -*- coding: utf-8 -*-
"""script_to_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16rC_TagB-cmJ25f_nyL10cfMTHxW0UB5
"""
import os
import pandas as pd
import time
from progress.bar import Bar

tests = pd.read_csv("fullfact_tests.csv", encoding = "ISO-8859-1")
test_name = ".\testplan-cassandra.jmx"


len = tests.shape[0]
bar = Bar("progress", max=len)

for i in range(len):
    if i <= 220:
        bar.next()
        continue
    command = ""
    command = \
        r"C:\Users\T-Gamer\Documents\apache-jmeter-5.4.1\apache-jmeter-5.4.1\bin\jmeter " + \
        r"-n -t .\testplan-cassandra.jmx -l " + r"results\fullfactorial\test001.jtl " + \
        f"-Jname=test_{tests['id'][i]} -Jinterval={tests['interval'][i]} " + \
        f"-Jusers={tests['users'][i]} -Jsize={int(tests['size'][i] * 14.85)} -Jconsistency={tests['consistency'][i]}"

    print(" id", i, "command", command)
    bar.next()
    os.system(command)
bar.finish()